### ISSUE TITLE
[Bug?] Incorrect percentage display

### ISSUE THREAD

**Issue by EvanHsieh0415** [Swedz/Mana-Visualizer#4]
![screenshot](https://user-images.githubusercontent.com/74277414/235420151-e060ec17-e40a-448d-b927-8f49aa5ee703.png)  
It should be 90%, but it is displaying 9%.  
The correct number should be the current percentage multiplied by 10.

**Comment by Swedz** [comment]
Mana pools store 1,000,000 mana. The percentage display here is based on a mana pool, not the bar displayed. Botania displays the bar in EMI/REI as 1/10th of a mana pool's capacity.
